##
# Setup File Template.
# Generated by Verigy 93000 VT (Version 1.10.8-3 [linux x86_64] 25-Nov-2020).
# (c) Copyright 1998-2022 Test Insight Ltd.
##

##############################
# Advantest 93000 Configuration
######

# 93k test program main directory ( Mandatory ).
_93k_testdir = '../../testprogram'

# 93k test flow file ( Mandatory ).
_93k_testflow = 'pattern_debug.tf'

# List of 93k test suite names to activate ( Optional ).
_93k_testsuites = ['SCAN'  ]

# Force automatic xmode decompression. (Optional, default = 0 )
_93k_force_x1 = 0


##############################
# VTB Generator Configuration
######

# Name of the device model. (Optional)
dut_name = "dut"

# Name of the top-level module. (Optional)
toplevel_module = "test_wrapper"

# Simulation time unit. (Optional)
time_unit = "1ps" # possible values are 100ns|10ns|1ns|100ps|10ps|1ps|100fs|10fs|1fs 

# Simulation precision. (Optional)
precision = "1ps" # possible values are 100ns|10ns|1ns|100ps|10ps|1ps|100fs|10fs|1fs 

# VT output directory. (Optional)
workdir = "vt_scan" # place to put the VT files

# Use of absolute paths in VT files, true by default. (Optional)
use_absolute_paths = 0

# Limit FSDB file size. (Optional, unlimited by default)
fsdb_file_size = -1

# Limit the number of FSDB files. (Optional)
fsdb_file_count = -1

# Rename signals. (Optional)
# Define a mapping between design signals and tester pins.
# Any signals not specified in the map will use original names.
# rename_signals = {  'design_pin_name1' : 'tester_pin_name1',  'design_pin_name2' : 'tester_pin_name2', ...   }

# Bus bit ordering. (Optional)
bus_ordering = "ascending" # possible values are ascending|descending 

# Testbench compatibility option. (Optional)
testbench_compatibility = "default" # possible values are default|cadence 

# Incremental mode, false by default. (Optional)
# When turned on, testbench generation will error out if any
# of the generated Verilog files are different than already existing ones.
incremental_mode = 0

# Minimum waveform count. (Optional)
# Generate at least the specified number of waveforms for each signal and each WFT.
# This option reduces the need to recompile Verilog code when new waveforms
# are added. If set to -1, actual number of waveforms will be generated.
min_waveform_count = -1

# Minimum vector count. (Optional)
# Generate the testbench for at least the specified number of vectors.
# This option reduces the need to recompile Verilog code when the size of
# the patterns changes. If set to -1, testbench will be generated for the
# actual number of vectors.
min_vector_count = -1

# Maximum vector count. (Optional)
# Generate the testbench in a way that no more than max_vector_count vectors
# are loaded at any given time in order to save memory and to ensure faster
# simulation times. If set to -1, testbench will be generated for the actual
# number of vectors (or for min_vector_count if it is set and higher than the
# actual number of vectors).
max_vector_count = -1

# Ground signals. (Optional)
# Allows to specify a list of DUT ground-level power supplies.
ground_signals = []

# Generate additional comments. (Optional)
verbose_mode = 0

# Keep intermediate STIL files (Optional)
keep_stil_files = 1

